### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by ggabogarcia** [finbargiusti/DrawTogether#1]
Hello sir :) I will open this problem to show you the design process, again thank you very much for contacting me :)

**Comment by ggabogarcia** [comment]
Here the sketches that I liked the most, all speak about "drawing together" 
[sketch1](https://i.imgur.com/HFeWGRU.jpg)  [sketch2](https://i.imgur.com/yrhmapE.jpg)  [sketch3](https://i.imgur.com/0TzdvRJ.jpg)   Tell me your opinion :)

**Comment by finbargiusti** [comment]
Wow that is really clever! I think that sketch 3 is my favourite but you're the expert so it's up to you. Love the work bud keep it up! 
:smile: @ggabogarcia

**Comment by ggabogarcia** [comment]
Yes I also like it :) then I will work with that  :muscle:  . And wow! thanks for your quick reply :)

**Comment by finbargiusti** [comment]
I get emails to my phone so I'm also quick to reply no matter where I am haha thanks for the work

**Comment by ggabogarcia** [comment]
Here the proposal :)
![drawtogether](https://user-images.githubusercontent.com/35750428/43428151-6f4d6f6a-9422-11e8-9027-b2ba9abfb026.png)

**Comment by ggabogarcia** [comment]
Test with colors, I choose as an example the landscape that is in the readme file for the colors :). You can suggest a combination that you like too.

![color](https://user-images.githubusercontent.com/35750428/43428236-f757e5d4-9422-11e8-9ca2-48611c86a04b.png)

**Comment by finbargiusti** [comment]
Wow! That looks great! Two notes  -

1. I have showed this to some of my peers and they didn't see the pencil in the design, as I did, maybe some kind of grading giving it edges or something would make it more obvious?
2. I would love if you could add some of the site's thematic jade colouring (#2ECC40)

Of course you are the experienced one, so please do as you feel is best

Keep it up man,

:smile_cat: 

e: out of the coloured ones, the one I like most is the first in the second row

**Comment by ggabogarcia** [comment]
Writing everything, I will make the changes :)

**Comment by ggabogarcia** [comment]
I think that by placing a stronger color and lengthening it a bit, the problem is solved with the pencil. What do you think? By the way that is the color you asked me for :smile_cat: 
![drawtogether2](https://user-images.githubusercontent.com/35750428/43429755-cbacdebe-942a-11e8-8b45-921026b8dff9.png)

**Comment by finbargiusti** [comment]
Looks amazing - Two more notes

1. Could you make it a little bit thinner?
2. Could you add on the title of the project - (DrawTogether) for the README and also the website landing page?

Once again, hugely appreciate all the work you're giving to this project.

Finbar

PS: I assume you'd like to be credited, and have your license shown, so just give me the details and I'll add them to the README right way

:smile_cat:

**Comment by ggabogarcia** [comment]
Of course! No logo is complete without the name, I will make the changes :)

**Comment by ggabogarcia** [comment]
Final proposal with the requested corrections :)

![drawtogether3](https://user-images.githubusercontent.com/35750428/43433772-75bb8302-943e-11e8-94e0-88e98dfa9571.png)

**Comment by finbargiusti** [comment]
Wow that looks great! One more thing and I think it would be perfect.

I think it would look even better if you put the bold on "together"
Either way great work and thank you again

Finbar

:smile_cat: 

E: Could you also Capitalize the "t" in together?

**Comment by ggabogarcia** [comment]
Hello :)  here are the changes. :smiley_cat: 
 
![drawtogether3](https://user-images.githubusercontent.com/35750428/43552988-96fe7d7e-95b2-11e8-8ac6-f05b8c548dd1.png)

**Comment by finbargiusti** [comment]
Wow! Thanks! Could you send it to me by email or make a pull request?

if you could just the side by side one and one logo only. Thank you so much once again!

:smile_cat:

**Comment by ggabogarcia** [comment]
Por correo lo puedo enviar :), No entendí la ultima parte, perdon jejej.

**Comment by finbargiusti** [comment]
No te preocupes

**Comment by ggabogarcia** [comment]
Te haré llegar todos los archivos, usted puede elegir con cual quedarse :1st_place_medal:.

**Comment by ggabogarcia** [comment]
Ready! sent files, please check that everything is fine. Anything else let me know :100:  :1st_place_medal:

**Comment by finbargiusti** [comment]
It's amazing! I love all the work you've done for DrawTogether. I'll credit you in the README. Do you have a license I need to reference for the logo?

:smile_cat:

**Comment by ggabogarcia** [comment]
Yeah, of course :) 

![DERECHOS.jpg](https://cdn.steemitimages.com/DQmVSH7hxt3nuyDxNRdWUBUBtfR11TyvLxM1F1C4vYW5UzG/DERECHOS.jpg)
This work is licensed under a [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/)

**Comment by finbargiusti** [comment]
Great work man! If I can help you in any way, just ask

**Comment by ggabogarcia** [comment]
Your quick response has been my help :100:  hehe, I was able to develop the work quickly :1st_place_medal:

**Comment by ggabogarcia** [comment]
Would you like this image for the readme? It just occurred to me

![portada](https://user-images.githubusercontent.com/35750428/43554249-f75711da-95b8-11e8-89a6-83203bee3e0f.png)

**Comment by finbargiusti** [comment]
Whoa yeah that looks great! If you could send that I'd like that very much.

**Comment by ggabogarcia** [comment]
I already added it to the Gdrive :muscle:

**Comment by finbargiusti** [comment]
Perfect! Thank you again for all the help! Closing this issue now
